spring:
  application:
    name: dailylog

  datasource:
    #Ambiente local
    #url: jdbc:mysql://localhost:3306/dailylog
    #username: root
    #password: CompuNueva1!

    #Ambiente de produccion
    url: jdbc:mysql://uultos5f3qzpwn1h:TDwUdZfGJEw7nJl0C93x@brii0efzkv9dfex5mjfl-mysql.services.clever-cloud.com:3306/brii0efzkv9dfex5mjfl
    username: uultos5f3qzpwn1h
    password: TDwUdZfGJEw7nJl0C93x


    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
